### ISSUE TITLE
Could you please provide SVMClassifier.xml?

### ISSUE THREAD

**Issue by pcchen-kid** [lishanlu136/FaceRecognition#1]
How's the accuracy of the SVM for anti-spoofing?
Could you please provide the pre-trained SVM file or the method how you trained it.
Thanks :)

**Comment by lishanlu136** [comment]
Sorry, this is just a demo project. The svm classifier used to combat spoofing faces extracts LBP features. If you want to improve the precision, you can use deep learning to extract features, then use svm to train the classifier, or directly classify with deep learning models, but that is only against a single disguise.
